### ISSUE TITLE
onChange arguments not in docs

### ISSUE THREAD

**Issue by dmitrika** [researchgate/react-intersection-observer#12]
Hello!

I was reading docs for the first time and it was unclear what arguments onChange receive. I had to open examples and get idea from them, or I could open src files. 

I suppose, we should add this information to documentation, for better dev. experience. If you are agree, I can do it :)

**Comment by Rendez** [comment]
@dmitrika you're right, it could be more explicit. I already wanted to update the options' format to a more concise block of text, I'll include your request alongside my changes.

**Comment by Rendez** [comment]
Ok, I've update the options section in the README file, let me know if that works ;)

https://github.com/researchgate/react-intersection-observer#options
