### ISSUE TITLE
Can't observe a React.Suspense element

### ISSUE THREAD

**Issue by arctouch-raphaellupchinski** [researchgate/react-intersection-observer#143]
## Expected behavior
Providing a React.Suspense as children to the Observer component renders it just fine

## Current behavior
Getting the "ReactIntersectionObserver: Can't find DOM node in the provided children. Make sure to render at least one DOM node in the tree." error when loading a lazily-loaded using React.Suspense and React.Lazy

## Steps to reproduce

1. Simply provide a Componente wrapped in a React.Suspense to the Observer component and it should break as soon as it becomes visible on screen

You can check the example on this sandbox: https://codesandbox.io/s/intersection-observer-suspense-lazy-owmrj?
Not that the `Component` renders normally, then the lazily-loaded loaded version of it loads as well, and finally, the same component wrapped by the `Observer` breaks unless we wrap it (lines 22-24) in a `div`.

## Context (environment)
We have a few components on a heavily accessed page that rely on lazy-loading to boost performance. We started noticing a few weeks ago that even after running the `unobserve` call for them after getting in view was still making the state changes (making the components unmount and mount again).
After updating the lib to v1.2.0 we started getting that "No DOM node" error for the components that used React.Suspense. 

* **Version**: 1.2.0 (intersection-observer at 0.10.0)
* **Platform**: Darwin raphael-lupchinski-mbp13-C02TF12ZFVH4.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64

**Comment by Rendez** [comment]
You can solve that using the `disabled` property on the `<Observer>` until the component loads. That can be tricky because React.lazy is defined outside the render method. I recommend you only use your VisibilityTracker outside the Suspense one.

**Comment by Rendez** [comment]
The hooks implementation just made it to master. I'll release a beta version now so you can test this out, because with hooks you'll be setting the component `ref` yourself, hence getting rid off this error.

**Comment by Rendez** [comment]
The hooks implementation 1.3.0 just got published, so you can test this out as well, because with hooks you'll be setting the component ref yourself, hence getting rid of this error.
