### ISSUE TITLE
npm is invalid on all releases

### ISSUE THREAD

**Issue by avalenti89** [researchgate/react-intersection-observer#154]
All the releases on npmJs are invalid since yesterday/today (I used 1.2.0v yesterday at 7:00 PM).

I can't use it anymore and it is very critical because it blocks my CI/CD production flow

**Comment by realestninja** [comment]
I have the same issue.

![image](https://user-images.githubusercontent.com/17706747/89525599-b9ed2d80-d7e6-11ea-89ee-9372b6b3e98a.png)

Installing this package is currently not possible.

```$ npm install --save @researchgate/react-intersection-observer
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@researchgate%2freact-intersection-observer - Not found
npm ERR! 404 
npm ERR! 404  '@researchgate/react-intersection-observer@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)```

**Comment by avalenti89** [comment]
https://status.npmjs.org/
It is a problem on entire npm registry. They are working on.

**Comment by Rendez** [comment]
Thanks for filing an issue anyway, glad it got resolved. We didn't realize because we run a nexus proxy in front of NPM.
