### ISSUE TITLE
Not observing when rerendered

### ISSUE THREAD

**Issue by Vince-vegas** [researchgate/react-intersection-observer#155]
I set each item(img) to have dataset and create a src attribute when its Intersecting = hot

but when I try to render different component eg. top_rated and rendered **hot** again it cannot create a src attribute

I set every item(MovieCard) to unobserve() after intersecting

code:

const handleChange = (entry, unobserve) => {
    if (entry.isIntersecting) {
      entry.target.setAttribute('src', entry.target.dataset.image);
      unobserve();
    }
  };

  const [ref] = useIntersectionObserver(handleChange);

items: 
<img dataset="..." ref={ref}/>

**Comment by Rendez** [comment]
Could you create a minimal example in codesanbox.io?

**Comment by Vince-vegas** [comment]
I finished fixing the bug 

I just use to fix it:
import **Observer** from '@researchgate/react-intersection-observer';

not the:
import { **useIntersectionObserver** } from '@researchgate/react-intersection-observer';

great work

**Comment by Vince-vegas** [comment]
Can I manually install some feature 

I just need the Observer only to minimize the file size

**Comment by Vince-vegas** [comment]
Can I manually install one feature

I just only use the **Observer** functionality not other the feature

to minimize the **file size**

**Comment by Rendez** [comment]
We can add `sideEffects: false` to package.json so that tools like webpack effectively do tree-shaking. I'll see what I can do.
In any case, can you create an example with codesandbox.io to see why hooks didn't work for your case?

**Comment by saitonakamura** [comment]
@Vince-vegas it was probably fixed in #173 , but since we don't have a clear repro of your issue, I can't be sure. Can I ask you to try and test hook in your case, if you have time?
