### ISSUE TITLE
Missing ajv peer dependency warning

### ISSUE THREAD

**Issue by janhoogeveen** [researchgate/react-intersection-observer#31]
# Expected behavior
Installing 0.6.1 returns no warnings

## Current behavior
```
λ npm install @researchgate/react-intersection-observer@0.6.1
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ @researchgate/react-intersection-observer@0.6.1
updated 1 package in 23.226s
```

## Steps to reproduce

1. Use 0.6.0 in your app
2. npm install @researchgate/react-intersection-observer@0.6.1

## Context (environment)

* **Version**: from 0.6.0 to 0.6.1 on NPM 5.8.0
* **Platform**:
Darwin Chrono.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Comment by Rendez** [comment]
Hi, I just run `npm install @researchgate/react-intersection-observer@0.6.1` on a new folder after `npm init` and I got no such warning. I also double-checked if the `ajv` package is at all installed by this repo with: `grep -rnw './node_modules' -e 'ajv'` but didn't find any match.

The only direct deps are `invariant` and `prop-types` and none of those require ajv or ajv-keywords, so it must be some your other package(s), you just didn't see it before.

**Comment by janhoogeveen** [comment]
I feel like a jackass for not checking if intersection-observer is the root cause. Thanks for your reply and sorry to trouble you :).
