### ISSUE TITLE
onlyOnce ambiguous behavior on first event

### ISSUE THREAD

**Issue by jayalfredprufrock** [researchgate/react-intersection-observer#32]
## Expected behavior
I expect when using `onlyOnce` option that unobserving should happen only after the observed item becomes visible, based on the threshold parameter (or in the case of an array of thresholds, when the _first_  threshold is met)

## Current behavior
In latest version of Chrome, the component stops observing even though the item is never visible. This is because Chrome can emit an event such that `isIntersecting` is true but `intersectionRatio` is still 0. I believe the spec requires that `isIntersecting` be true _and_ `intersectionRatio > 0` for something to be considered visible.

## Steps to reproduce
Not sure exactly how to recreate the conditions necessary for Chrome to emit such an event...

* **Version**:  latest

Adding an additional condition before unobserving here: 

https://github.com/researchgate/react-intersection-observer/blob/69e297f895188177fc8c5f9345ffb152e6e43866/src/IntersectionObserver.js#L114

to also check for `intersectionRatio != 0` fixed the issue for me.

**Comment by Rendez** [comment]
The W3C [specification states](https://w3c.github.io/IntersectionObserver/#dom-intersectionobserverentry-isintersecting) that edge-adjacent intersections and zero-area intersections are truthy. Chrome adheres pretty well to the last spec review. I tried Chrome 65 and 66 and both behave as expected in the example: https://researchgate.github.io/react-intersection-observer/iframe.html?selectedKind=Examples&selectedStory=Once

The `threshold` prop will have an effect on how Chrome triggers the event with `isIntersecting` being true. For example this:
```jsx
<Observer onChange={this.handleChange} onlyOnce={true} threshold={[1]}>
```
Will only stop unobserving after the entire element has entered the viewport, meaning, `intersectionRatio` is 1. If you want to avoid the zero-area matching, you could use a threshold value of say `0.01` to make it work as you want it to.

If the error persists for you, and you can provide a working example, feel free to re-open this issue :)

**Comment by jayalfredprufrock** [comment]
Thanks for pointing me to the relevant spec. Unfortunately I still receive an IntersectionObserverEntry event with `isIntersection=true` and `intersectionRatio=0` even when my threshold is > 0. This is in Chrome 66. I'll try and put together an example that demonstrates this behavior but I'm positive at least the above _can_ happen.

**Comment by jayalfredprufrock** [comment]
I tracked down the issue to normalize.css. 

With normalize.css included I was able to create a very simple example that demonstrates the behavior I'm seeing:

https://codesandbox.io/s/nnqr6z5mxm

I couldn't tell you exactly who is to blame or if there is anything technically out of spec. It's not terribly difficult to work around this problem, but I wanted to follow up nonetheless since including normalize.css is probably pretty common and I imagine many people using your package for animation would want to take advantage of `onlyOnce`.  Cheers

**Comment by Rendez** [comment]
Thanks for the example. I had a real look into it this time with Firefox and Safari (w/ the polyfill). All portray the same behavior: edge-adjacent intersections, as by spec.

As you have proven yourself, setting a threshold doesn't behave as expected on initial load, and that's because what setting threshold(s) does it to register the points at which subsequent entries will be emitted. However, this doesn't change the fact that that we receive the initial event with an adjacent match.

The initial event *always* happens in all browsers (used to not be the case a year ago). That means in the example you're doing the right thing, using the `intersectionRatio` (which would work w/out `isIntersecting`):
```jsx
this.setState({
      isIntersecting: e.isIntersecting && e.intersectionRatio > 0
    });
```

Since all browsers behave the same way, this isn't a Chrome 66 issue, this is really how the spec is drafted and `onlyOnce` is therefore is correct – if we'd append `intersectionRatio > 0` then we'd jeopardize those cases relying on zero-area matches.
I try for this library to be a thin layer on top of the native API, so that the expectations are the same as using the API on its own, that way everyone is able to adapt things for each use case.

I propose you achieve what you want by:
1. `calc(100vh + 1px)`
2. instead of using `onlyOnce`, setting [`disabled=true`](https://github.com/researchgate/react-intersection-observer#options) after your example matches `intersectionRatio > 0`

**Comment by jayalfredprufrock** [comment]
Thanks for the response, really appreciate it. Now that I understand the situation more, I agree that appending `intersectionRatio > 0` could screw up other cases. Instead, I think a solution to get the best of both worlds would be to have `onlyOnce` behave differently depending on whether `threshold = 0`.  Something like this:

```
const thresholdIsZero = Array.isArray(threshold) ? threshold.includes(0) : !threshold;
if (isIntersecting && (thresholdIsZero || intersectionRatio != 0)) {
       this.unobserve();
}
``
IMHO this would lead to more expected behavior when using `thresholds > 0` in combination with `onlyOnce`. Anyways, I've already used the `disabled` prop as you describe to work around this so i'll leave now :) thanks for your time.

**Comment by Rendez** [comment]
@jayalfredprufrock I really think it's a nice proposal, but somehow we'd be using threshold=0 to do something that the native API doesn't, thus modifying behavior. What we really need is a custom `isIntersecting` callback, so that we can define what `visible/invisible` means, and that is also used by `onlyOnce`. What do you think?
```

**Comment by jayalfredprufrock** [comment]
Yeah that would definitely add a bit more flexibility and solve my particular use case. On the other hand, its a bit ironic that one of the only features in the library that _isn't_ just exposing the underlying API is what's causing the issue for me. Have you considered removing/deprecating the `onlyOnce` property altogether and beefing up the HoC example to include such behavior? That's what I ended up doing and I'm pretty satisfied with the results so far. 

```
import React, { Component } from 'react';
import 'intersection-observer'; //polyfill
import Observer from '@researchgate/react-intersection-observer';
import classnames from 'classnames';

const withVisibilityMonitor = (defaultOptions = {}) => BaseComponent => {

  const displayName = BaseComponent.displayName || BaseComponent.name || 'Component';

  const {
    monitorVisibility = false,
    visibleClassName = 'visible',
    hiddenClassName = '', 
    triggerOnce = true,
    threshold = .25,
    ...observerProps
  } = defaultOptions;

  return class VisibilityHOC extends Component {
    
    static displayName = `withVisibilityMonitor(${displayName})`;

    constructor(props){

      super(props);

      this.state = {
        isVisible: false
      };

      this.listeners = [];
    }

    getChildContext() {
      return {
        addVisibilityListener: this._addVisibilityListener,
        removeVisibilityListener: this._removeVisibilityListener
      };
    }

    componentWillUnmount() {

      this.listeners = [];
    }
    
    render() {

      const {
        monitorVisibility, visibilityThreshold, 
        className, visibleClassName, hiddenClassName, 
        triggerVisibilityOnce, intersectionObserverProps, 
        ...extraProps 
      } = this.props; 
        
      const {isVisible} = this.state;

      const mergedClassName = classnames(className, {[visibleClassName]: isVisible, [hiddenClassName]: !isVisible});
      
      const mergedObserverProps = Object.assign({}, observerProps, intersectionObserverProps, {
        onChange: this._onIntersectionObserverChange,
        threshold: visibilityThreshold,
        disabled: !monitorVisibility || (triggerVisibilityOnce && isVisible)
      });

      return (
        <Observer {...mergedObserverProps}>
          <BaseComponent 
            className={mergedClassName}
            isVisible={isVisible} 
            {...extraProps} 
          />
        </Observer>
      );
    }

    _onIntersectionObserverChange = ({isIntersecting, intersectionRatio}) => {

      const {visibilityThreshold} = this.props;
      const {isVisible} = this.state;

      const thresholdIsArray = Array.isArray(visibilityThreshold);
      const thresholdValue = thresholdIsArray ? (visibilityThreshold[0] || 0) : visibilityThreshold;

      this.setState({isVisible: isIntersecting && (!thresholdValue || intersectionRatio >= thresholdValue)});

      for (const listener of this.listeners){

          listener({isVisible});
      }

    }

    _addVisibilityListener = (listener) => {

      if (!this.listeners.includes(listener)){
  
          this.listeners.push(listener);
      }
    }
  
    _removeVisibilityListener = (listener) => {
  
      this.listeners = this.listeners[type].filter(l => l !== listener);
    }

    static childContextTypes = {
      addVisibilityListener: PropTypes.func,
      removeVisibilityListener: PropTypes.func
    };

    static propTypes = {
    
      monitorVisibility: PropTypes.bool,
      visbilityThreshold: PropTypes.oneOfType([PropTypes.number, PropTypes.arrayOf(PropTypes.number)]),
      visibleClassName: PropTypes.string,
      hiddenClassName: PropTypes.string,
      triggerVisibilityOnce: PropTypes.bool,
      intersectionObserverProps: PropTypes.object      
    };
  
    static defaultProps = {
  
      monitorVisibility: monitorVisibility,
      visibilityThreshold: threshold,
      visibleClassName: visibleClassName,
      hiddenClassName: hiddenClassName,
      triggerVisibilityOnce: triggerOnce
  
    };

  }
};

export default withVisibilityMonitor;
```

**Comment by Rendez** [comment]
You got a really good point. Because the first event emitted doesn't not account for `rootMargin`, nor `threshold`, then `onlyOnce` as a means to specify `this element is visible` it's ambiguous to the very least. I will be deprecating `onlyOnce` and I'll consider including an official example instead.

**Comment by Rendez** [comment]
@jayalfredprufrock I've submitted a PR deprecating `onlyOnce` and adding a new callback to `onChange`. Let me know your thoughts on it.

**Comment by Rendez** [comment]
So, ideally I would like to have `isIntersecting/intersectionRatio` feedback on the first event even within iframes (like it happens on codesandbox or storybook). That way you could always use `rootMargin=-1px 0px` to avoid accounting for edge-adjacent intersections. I've opened [an issue](https://github.com/w3c/IntersectionObserver/issues/283#issuecomment-389153942) to try and figure out what's the plan on supporting this prop correctly.

**Comment by jayalfredprufrock** [comment]
Nice work! I think this is a solid improvement. I too am curious about the iframe/root margin intended behavior. I guess we'll see what they say over there.
