### ISSUE TITLE
Ability to specify refKey prop

### ISSUE THREAD

**Issue by rifler** [researchgate/react-intersection-observer#41]
i.e. in styled-components prior to v4, you have to use `innerRef` instead of `ref`.
Did I understand correctly that this doesn't work now?

https://www.styled-components.com/docs/api#innerref-prop

**Comment by Rendez** [comment]
The solution for versions below v4 would be to wrap your styled components with an html element (div, span, etc.) so that our react component can attach `ref` to it.

**Comment by Rendez** [comment]
I'll close this issue as it's something that depends on the library and has a fairly simple solution.
