### ISSUE TITLE
Support for horizontal offsets (?)

### ISSUE THREAD

**Issue by shelldandy** [researchgate/react-intersection-observer#42]
For stuff like sliders and what not 👅 

Just wondering if this library can do that :)

**Comment by Rendez** [comment]
Yes it can, here's an example: https://researchgate.github.io/react-intersection-list/?selectedKind=Examples&selectedStory=X-Axis&full=0&down=0&left=1&panelRight=0

And if you need padding, just set the `rootMargin` for horizontal edges with a value similar to "0% 25%", just like you would for CSS padding/margin props.

**Comment by shelldandy** [comment]
Sweet! Thanks a lot 😄
