### ISSUE TITLE
ReferenceError: Can't find variable: IntersectionObserver when testing on Safari Version 11.0.3

### ISSUE THREAD

**Issue by randmem** [researchgate/react-intersection-observer#49]
## Expected behavior
Using Observer in the app should not report any errors inside node_modules. The current usage on our side works on chrome, firefox and other browsers. Expected behaviour is to have Observer work in Safari the way it is working on other browsers. 

## Current behavior
On safari and Safari only: 

ReferenceError: Can't find variable: IntersectionObserver
observe
node_modules/react-intersection-observer/dist/react-intersection-observer.esm.js:102
   99 | var observerInstance = observerId ? OBSERVER_MAP.get(observerId) : null;
  100 | 
  101 | if (!observerInstance) {
> 102 |   observerInstance = new IntersectionObserver(onChange, options);
      | ^  103 |   if (observerId) OBSERVER_MAP.set(observerId, observerInstance);
  104 | }
  105 | 

## Steps to reproduce
1. Go to https://greenrush-spa.herokuapp.com/menu on Safari
2. Go to same link on Chrome and other browsers

## Context (environment)
Can't find variable: IntersectionObserver when testing on Safari Version 11.0.3
ReferenceError: Can't find variable: IntersectionObserver
observe
node_modules/react-intersection-observer/dist/react-intersection-observer.esm.js:102
   99 | var observerInstance = observerId ? OBSERVER_MAP.get(observerId) : null;
  100 | 
  101 | if (!observerInstance) {
> 102 |   observerInstance = new IntersectionObserver(onChange, options);
      | ^  103 |   if (observerId) OBSERVER_MAP.set(observerId, observerInstance);
  104 | }
  105 | 

* **Version**: 6.2.3
* **Platform**: Mac OS High Sierra 10.13.3

**Comment by Rendez** [comment]
Last time I checked, Safari [requires a polyfill](https://github.com/researchgate/react-intersection-observer#polyfill) which was documented. Are you using a version with or without IntersectionObserver native support?
