### ISSUE TITLE
Confusion: Two packages with the same name

### ISSUE THREAD

**Issue by raRaRa** [researchgate/react-intersection-observer#50]
What's the difference between this and https://github.com/thebuilder/react-intersection-observer

Both are almost identical in many ways, and actively maintained. Which one should I choose?

Thanks!

**Comment by Rendez** [comment]
Hi, you're right that they're both actively maintained. Both packages have solid APIs and are durable. Pick what works best for your case by having a look at the docs and examples.

This library used to have the advantage that it reused instances based on the prop serialization automatically. Both things are also now available in the other one (although you need to use the prop `rootId` and keep track of that manually.

Another subtle difference is that we handle refs internally for you, so you don't have to specify the "mount" node (we will find it for you).

Ultimately, we also do not have a `triggerOnce` prop, [we found that it ambiguous](https://github.com/researchgate/react-intersection-observer/issues/32) and removed it in favour of a callback argument on `onChange`.

In the end, both libraries allow you to do the same and are performant and small in size at this point in time.

Overtime, some projects grow apart and others they grow closer in behavior. We developed this library internally at ResearchGate and use it in production very extensively, so back then we decided to open source.

I hope that clarifies things a bit more. The decision is yours!

**Comment by raRaRa** [comment]
Thank you for the excellent answer! I will definitely have to think about this, both look so great! 👍
