### ISSUE TITLE
Class Wrapper for Stateless Functional Components

### ISSUE THREAD

**Issue by helloitsjoe** [researchgate/react-intersection-observer#51]
Hello! I'm running into an issue with observing stateless functional components (because they can't be given refs), and a potential solution I've found is wrapping the component in a class component that does nothing but returns the child:
```
class SFCWrapper extends React.Component {
  render() {
    return React.Children.only(this.props.children);
  }
}
```
This seems to handle the ref, but I'm wondering if this is a viable solution, or will this cause problems I'm not seeing?

**Comment by Rendez** [comment]
Hi, that is exactly what we do as well. In our case with `recompose/toClass`.

Note that we're preparing an update to React 16 where we won't be using `findDOMNode` anymore and it'll require you to use `React.forwardRef()`, so perhaps you want to start doing that to assign the ref to the actual DOM element you wish to observe.

**Comment by helloitsjoe** [comment]
That's super helpful, thanks so much!
