### ISSUE TITLE
Positive rootMargin ignored on horizontal axis

### ISSUE THREAD

**Issue by gsaynac** [researchgate/react-intersection-observer#53]
Hello ✌️

## Expected behavior
When using positive rootMargin on the right edge, the root element's bounding box should grow in that direction.

## Current behavior
The root element's bounding box acts like there are no margins applied.

## Context
- I am using this component to lazy load various scripts on the horizontal axis.
- The root is the document's viewport (I didn't specify anything actually).
- This works fine on the vertical axis, or with margins <= 0.
- No iFrame involved (I've read the issues with iFrames).

## Code
I use it in many cases, one of them being a classic infinite scroll pattern, such as (simplified) : 
```
<MyHorizontalList>
  <MyElements />
  <Observer rootMargin="0px 1000px 0px 0px" onChange={this.handleObserverEvent}>
    <MyTrigger />
  </Observer>
</MyHorizontalList>
```
## Screenshot
The most intriguing thing is that **the rootBounds has the added margin** on the right edge and I think it should intersect according to what I logged 🤔

![screenshot 2018-12-18 at 15 30 29](https://user-images.githubusercontent.com/6241539/50165666-a75a7380-02e5-11e9-936e-23a9624fc1f3.png)

I used 1Mpx margin just to make the example easier, but the behaviour is identical with regular margins.

Thanks !

**Version**: 0.7.4
**Platform**: Chrome 71 on macOS (Mojave)

**Comment by Rendez** [comment]
Hi, without looking much into details, I can tell that you don't specify a root. That means that it defaults to the main viewport (window). Normally for infinite lists you'd need to assign your `MyHorizontalList` as the root. Example: https://github.com/researchgate/react-intersection-list/blob/master/src/List.js#L74

**Comment by gsaynac** [comment]
Thanks @Rendez, I managed to make it work by specifying the correct root.

Just for the record, I am using https://github.com/kidjp85/react-id-swiper, so the correct root was `.swiper-container` by default.

Still, I am intrigued by why it was working fine on the vertical axis, or with margins <= 0 🤔

Anyway, thanks again 🙏
