### ISSUE TITLE
`process` is undefined

### ISSUE THREAD

**Issue by adhithyar** [researchgate/react-intersection-observer#55]
We are utilizing the react-intersection-observer.umd.min.js for a project we are working on.

## Expected behavior
When the browser loads the react-intersection-observer module, it should load without errors. 

## Current behavior
When we import the react-intersection-observer module, it errors out with the following error message - 
`process` is undefined.  Digging through the code, we noticed that even on distribution version of the builds, we are trying to check if `process.env.NODE_ENV == "production"`. Since we are running on the browser, it makes sense why Node's process will be undefined. 

## Steps to reproduce
1. npm install react-intersection-observer
2. Create a small app that uses react-intersection-observer
3. Try to load the react-intersection-observer module through UMD via requirejs
4. Look at the browser console.

## Context (environment)
We are not using webpack. We have our own custom build tooling. 

* **Version**: 6.3.1
* **Platform**: Windows 10 64 Bit

**Comment by Rendez** [comment]
Are you loading the umd.min.js build from this source: https://github.com/thebuilder/react-intersection-observer/blob/master/package.json#L7 ?

**Comment by Rendez** [comment]
If so, you could consider migrating to our library instead 😉
