### ISSUE TITLE
Library not working on iOS 12 and Next.js

### ISSUE THREAD

**Issue by MatteoGioioso** [researchgate/react-intersection-observer#58]
Looks like the library is miss behaving for iOS version below 12, but I am not sure 100%.
On Android, Windows and Linux it works normally.

## Expected behavior
Working normally

## Current behavior
I receive this error

```invocation exception on Object.childNodeCountUpdated(): TypeError: Cannot set property '_childNodeCount' of undefined```

This is happening only in iOS and I could test only with version 12.0.1
I am using `next.js` I am not sure is happening with vanilla `react.js` also.

## Steps to reproduce
I will try to provide a codesandbox and more information as I keep investigating, but it should pretty easy to reproduce.

## Context (environment)
I am using:

```
Next.js: 8.0.3
react: 16.8.1,
react-dom: 16.8.1
```

```
Chrome: 73.0
```

* **Version**:  0.7.4
* **Platform**: iOS 12.0.1

**Comment by Rendez** [comment]
I'll just throw a rock out there:
- are you using the polyfill? https://github.com/w3c/IntersectionObserver/issues/315
- seems like you would since the native API is only availble on iOS 12.2 onwards... https://webkit.org/blog/8582/intersectionobserver-in-webkit/

**Comment by MatteoGioioso** [comment]
@Rendez I just realized that `next.js` was not loading the polyfill correctly.
Silly me, sorry for the trouble
