### ISSUE TITLE
[Bug] Module 'invariant' not found on production environments

### ISSUE THREAD

**Issue by connor-baer** [researchgate/react-intersection-observer#6]
## Expected behavior
The `invariant` module appears to be used only for debugging purposes on non-production environments, so it shouldn't need to be installed on production environments.

## Current behavior
When building my project with `webpack` for production, an error is thrown: 

```bash
ERROR in ./node_modules/@researchgate/react-intersection-observer/lib/es/IntersectionObserver.js
Module not found: Error: Can't resolve 'invariant' in '~/Projects/website/node_modules/@researchgate/react-intersection-observer/lib/es'
 @ ./node_modules/@researchgate/react-intersection-observer/lib/es/IntersectionObserver.js 12:0-34
 @ ./node_modules/@researchgate/react-intersection-observer/lib/es/index.js
 @ ./src/components/ProductPaymentMethods.js
 @ ./src/pages/Page.js
 @ ./src/App.js
 @ ./server/render.js
 @ ./server/app.js
 @ ./server/index.js
```

I assume this happens since `npm` doesn't install devDependencies on production environments. `IntersectionObserver` tries to import `invariant` (although it's not used) and then fails to find it.

## Steps to reproduce

1. Use `IntersectionObserver` in a project
2. Compile the project with webpack in a production environment
3. Tada! 🎉 

## Context (environment)

* **Version**: 0.3.0
* **Platform**: x86_64 GNU/Linux

**Comment by danez** [comment]
Thanks for reporting this bug. This is obviously wrong, seems we made a mistake there.

Will release a new version tomorrow.
