### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by abusada** [researchgate/react-intersection-observer#63]
Hello, i get the following error when i `npm install`, 

> error @researchgate/react-intersection-observer@1.0.1: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "8.11.4"

is the `engine` field necessary here for a browser targeted library?

**Comment by Rendez** [comment]
Hi, if I remember correctly, node 10 is required to install some of the `devDependencies`, in particular [spire](https://github.com/researchgate/spire/tree/master/packages/spire). Try `npm install --production` to install only `dependencies` instead, or use a Node version >= 10.
