### ISSUE TITLE
Observer type error

### ISSUE THREAD

**Issue by Sir-hennihau** [researchgate/react-intersection-observer#68]
## Expected behavior
Webpack should compile, no type error should occur

## Current behavior
Webpack throws a typescript error

## Steps to reproduce
```
const Component = () => {
  const handleIntersection = (event: any) => {
    console.log(event);
  }

  return (
    <Observer onChange={handleIntersection}>
      <div>Content</div>
    </Observer>
  );
}
```

I tried also something like this

```
  const handleIntersection = (event: IntersectionObserverEntry) => {
    console.log(event);
  }

```

## Context (environment)

Error:
```
TS2322: Type '{ children: any[]; onChange: (event: IntersectionObserverEntry) => null; }' is not assignable to type 'Readonly<Props>'.
  Types of property 'children' are incompatible.
    Type 'any[]' is missing the following properties from type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<any, any, any>)>': type, props, key
```

* **Version**: ^1.0.1
* **Platform**: Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Rendez** [comment]
Thanks for reporting this. If you have time to open a PR, I would gladly review and approve it.

**Comment by Rendez** [comment]
I'll be releasing a TypeScript version of this package very soon.

**Comment by Rendez** [comment]
Done, you will find now the correct types if you upgrade to 1.2.0
