### ISSUE TITLE
Deprecated `findDOMNode` usage

### ISSUE THREAD

**Issue by OliverJAsh** [researchgate/react-intersection-observer#74]
`findDOMNode` usage: https://github.com/researchgate/react-intersection-observer/blob/83e69e271d9a21577d1749bc938d776677be144e/src/IntersectionObserver.js#L105

This is now deprecated: https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage.

This means users of this library will not be able to use concurrent mode, as it does not support `findDOMNode`: https://reactjs.org/docs/concurrent-mode-adoption.html#feature-comparison.

**Comment by Rendez** [comment]
This is in our bucket list. The plan would be to support `findDOMNode` as a fallback for a while, but make it so that usages have to forward the ref, e.g.:

```jsx
render() {
  const { children } = this.props;
  return children != null
      ? React.cloneElement(React.Children.only(children), {
            ref: this.handleNode,
        })
      : null;
}
// [...]
handleNode() {
  // [...]
  if (target instanceof HTMLElement) {
    this.targetNode = target;
  } else {
    console.warn('The ref must be forwarded to a DOM node, the findDOMNode() fallback will be deprecated');
    this.targetNode = target && findDOMNode(target);
  }
}
```

**Comment by Rendez** [comment]
We might not do this after #130 gets merged, and instead prompt users to utilize the hooks implementation. This is bold thought, what do you think of that?

**Comment by OliverJAsh** [comment]
I would prefer to have the choice of still using the non-hooks versions, e.g. in class components.

**Comment by Rendez** [comment]
I thought so. Ok I had that planned too, but it's a breaking change. Do you feel like issuing a PR? Otherwise I need a bit of time to get around it.

**Comment by Rendez** [comment]
I've decided to not move forward with re-implementing this without hooks for now. Use the hooks version by wrapping your components using a HOC for example (or render props), so that you can pass the `ref` down to your observing element, like this:
```js
function withIntersectionObserver(Component) {
  return (props) => {
    const [ref] = useIntersectionObserver(onChange);
    return <Component {...props} intersectionObserverRef={ref} />
  }
}
```

**Comment by OliverJAsh** [comment]
To be clear, is `findDOMUsage` now removed?
